/* automatically generated by rust-bindgen 0.65.1 */

extern "C" {
    pub fn crc64_init();
}
extern "C" {
    pub fn crc64_append(crc: u64, input: *const ::std::os::raw::c_void, sz: usize) -> u64;
}
extern "C" {
    pub fn crc64_srand(seed: u64);
}
extern "C" {
    pub fn crc64_rand() -> u64;
}
extern "C" {
    pub fn crc64_rand_fract() -> f64;
}
extern "C" {
    pub fn crc64_rand_normal(sigma: f64) -> f64;
}
